name: "Check if PR is WIP"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  prIsWip:
    name: PR is WIP?
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - id: pr-is-wip
        uses: shiipou/pr-is-wip-action@v1.0.0-beta.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  main:
    needs: 
     - prIsWip
    if: ${{ needs.prIsWip.outputs.isWip }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: |
          echo "test: ${{ needs.prIsWip.outputs.isWip }}"
