name: "Check if PR is WIP"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  prIsWip:
    name: PR is WIP?
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      isWip: ${{ steps.prIsWip.outputs.isWip }}
    steps:
      - id: prIsWip
        uses: shiipou/pr-is-wip-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "test: ${{ toJSON(steps) }}"

  main:
    needs: 
     - prIsWip
    if: needs.prIsWip.outputs.isWip == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: |
          echo "My work !!"
